const path=require("path")
console.log(path.sep)
const filePath=path.join('content','subfolder',"nw.txt")
console.log(filePath)
const base=path.basename(filePath)
console.log(base)
const absolute=path.resolve(__dirname,filePath)
console.log(absolute)
console.log(path)
/* const os=require('os')
const user=os.userInfo()
console.log(user)
console.log(os.uptime())
console.log(os.totalmem())
console.log(os.release())
console.log(os.freemem())
console.log(os.cpus())
console.log(os.type())
console.log(os.version())
console.log(os)
console.log(os.arch())
console.log(os.tmpdir()) */